server:
    port: 8082
spring:
    application:
        name: approval-service
    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:postgresql://localhost:5433/expense-db
        username: admin
        password: admin
